<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pages".
 *
 * @property integer $id
 * @property string $short_address
 * @property string $long_address
 * @property string $created_at
 */
class Page extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pages';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['long_address'], 'string'],
            [['long_address'], 'required'],

            [['short_address'], 'string', 'max' => 255],
            [['short_address'], 'unique'],

            [['created_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'short_address' => 'Short Address',
            'long_address' => 'Long Address',
            'created_at' => 'Created At',
        ];
    }

    public function beforeSave($insert)
    {
        $short_address = substr(md5(microtime()), rand(0, 26), 6);
        $this->short_address = $short_address;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function findByUrl($url){
        return self::find()->where([
            'short_address' => $url
        ])->one();
    }
}
